# Generated by Django 6.0 on 2025-12-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Backend Name')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Display Name')),
                ('continent', models.CharField(blank=True, max_length=50, verbose_name='Continent')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Country Code')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is Available')),
                ('documentation_url', models.URLField(blank=True, null=True, verbose_name='Documentation URL')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='Site URL')),
                ('status_url', models.URLField(blank=True, null=True, verbose_name='Status URL')),
            ],
            options={
                'verbose_name': 'Backend',
                'verbose_name_plural': 'Backends',
                'ordering': ['continent', 'country_code', 'name'],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Company description', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='companyatla_created_0b2299_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')", max_length=100, verbose_name='Source')),
                ('country_code', models.CharField(help_text='ISO country code (e.g., FR, US, GB)', max_length=2, verbose_name='Country Code')),
                ('data_type', models.CharField(help_text='Type of data (e.g., denomination, siren, capital, employees)', max_length=100, verbose_name='Data Type')),
                ('value', models.TextField(help_text='Data value', verbose_name='Value')),
                ('value_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('json', 'JSON')], default='str', help_text='Type of the value (str, int, float, json)', max_length=10, verbose_name='Value Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(help_text='Company this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='companyatlas.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Data',
                'verbose_name_plural': 'Company Data',
                'indexes': [models.Index(fields=['company', 'country_code'], name='companyatla_company_44f20a_idx'), models.Index(fields=['data_type'], name='companyatla_data_ty_c72636_idx')],
                'unique_together': {('company', 'source', 'country_code', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')", max_length=100, verbose_name='Source')),
                ('country_code', models.CharField(help_text='ISO country code (e.g., FR, US, GB)', max_length=2, verbose_name='Country Code')),
                ('document_type', models.CharField(help_text='Type of document (e.g., bodacc, kbis, balo)', max_length=100, verbose_name='Document Type')),
                ('title', models.CharField(help_text='Document title', max_length=255, verbose_name='Title')),
                ('date', models.DateField(blank=True, help_text='Document date', null=True, verbose_name='Date')),
                ('url', models.URLField(blank=True, help_text='URL to access the document', verbose_name='URL')),
                ('content', models.TextField(blank=True, help_text='Document content or summary', verbose_name='Content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional document metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(help_text='Company this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companyatlas.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
                'indexes': [models.Index(fields=['company', 'country_code'], name='companyatla_company_9dca39_idx'), models.Index(fields=['document_type'], name='companyatla_documen_4dfbff_idx'), models.Index(fields=['date'], name='companyatla_date_85492c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')", max_length=100, verbose_name='Source')),
                ('country_code', models.CharField(help_text='ISO country code (e.g., FR, US, GB)', max_length=2, verbose_name='Country Code')),
                ('event_type', models.CharField(help_text='Type of event (e.g., status_change, modification, capital_change)', max_length=100, verbose_name='Event Type')),
                ('title', models.CharField(help_text='Event title', max_length=255, verbose_name='Title')),
                ('date', models.DateField(blank=True, help_text='Event date', null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, help_text='Event description', verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(help_text='Company this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companyatlas.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Event',
                'verbose_name_plural': 'Company Events',
                'indexes': [models.Index(fields=['company', 'country_code'], name='companyatla_company_d434e9_idx'), models.Index(fields=['event_type'], name='companyatla_event_t_d841b7_idx'), models.Index(fields=['date'], name='companyatla_date_127b4d_idx')],
            },
        ),
    ]
