# Generated by Django 6.0 on 2025-12-09 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companyatlas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackendInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Backend Name")),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Display Name"),
                ),
                (
                    "continent",
                    models.CharField(blank=True, max_length=50, verbose_name="Continent"),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=2, verbose_name="Country Code"),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="Is Available"),
                ),
            ],
            options={
                "verbose_name": "Backend",
                "verbose_name_plural": "Backends",
                "ordering": ["continent", "country_code", "name"],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CompanyCountryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(help_text="ISO country code (e.g., FR, US, GB)", max_length=2),
                ),
                (
                    "siren",
                    models.CharField(
                        blank=True,
                        help_text="French SIREN number (9 digits)",
                        max_length=9,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(9)],
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True,
                        help_text="French SIRET number (14 digits)",
                        max_length=14,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                (
                    "rna",
                    models.CharField(
                        blank=True,
                        help_text="French RNA number (W + 8 digits)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "ape",
                    models.CharField(
                        blank=True,
                        help_text="French APE/NAF code",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        help_text="Legal form (SARL, SA, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "rcs",
                    models.CharField(
                        blank=True,
                        help_text="RCS registration number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional country-specific data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Country Data",
                "verbose_name_plural": "Company Country Data",
            },
        ),
        migrations.CreateModel(
            name="CompanyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(help_text="ISO country code (e.g., FR, US, GB)", max_length=2),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="Type of data (e.g., denomination, siren, capital, employees)",
                        max_length=100,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        help_text="Type of the value (str, int, float, json)",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Data value (stored as string, converted based on value_type)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Data",
                "verbose_name_plural": "Company Data",
            },
        ),
        migrations.RemoveIndex(
            model_name="company",
            name="companyatla_siren_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="companyatla_domain_136ba2_idx",
            old_name="companyatla_domain_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="companyatla_vat_num_5cb20e_idx",
            old_name="companyatla_vat_num_idx",
        ),
        migrations.RenameIndex(
            model_name="company",
            new_name="companyatla_created_0b2299_idx",
            old_name="companyatla_created_idx",
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO country code (e.g., FR, US, GB)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Company domain (e.g., example.com)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="VAT/Tax identification number (international)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["country"], name="companyatla_country_079832_idx"),
        ),
        migrations.AddField(
            model_name="companycountrydata",
            name="company",
            field=models.ForeignKey(
                help_text="Company this data belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country_data",
                to="companyatlas.company",
            ),
        ),
        migrations.AddField(
            model_name="companydata",
            name="company",
            field=models.ForeignKey(
                help_text="Company this data belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="companyatlas.company",
            ),
        ),
        migrations.RemoveField(
            model_name="company",
            name="siren",
        ),
        migrations.AddIndex(
            model_name="companycountrydata",
            index=models.Index(
                fields=["company", "country"], name="companyatla_company_257333_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companycountrydata",
            index=models.Index(fields=["country", "siren"], name="companyatla_country_4cac4c_idx"),
        ),
        migrations.AddIndex(
            model_name="companycountrydata",
            index=models.Index(fields=["siren"], name="companyatla_siren_5448cd_idx"),
        ),
        migrations.AddIndex(
            model_name="companycountrydata",
            index=models.Index(fields=["siret"], name="companyatla_siret_7f1a60_idx"),
        ),
        migrations.AddIndex(
            model_name="companycountrydata",
            index=models.Index(fields=["rna"], name="companyatla_rna_66474f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="companycountrydata",
            unique_together={("company", "country")},
        ),
        migrations.AddIndex(
            model_name="companydata",
            index=models.Index(
                fields=["company", "country"], name="companyatla_company_6cc064_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companydata",
            index=models.Index(
                fields=["country", "data_type"], name="companyatla_country_f2762f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companydata",
            index=models.Index(fields=["data_type"], name="companyatla_data_ty_c72636_idx"),
        ),
        migrations.AddIndex(
            model_name="companydata",
            index=models.Index(fields=["value_type"], name="companyatla_value_t_aadc9c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="companydata",
            unique_together={("company", "country", "data_type")},
        ),
    ]
