# Generated by Django 6.0.1 on 2026-01-22 13:05

import django.db.models.deletion
import djgeoaddress.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyAtlasProviderModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Provider name (e.g., insee)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Provider display name", verbose_name="Display Name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Provider description", verbose_name="Description"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Provider priority", verbose_name="Priority"
                    ),
                ),
                (
                    "config_status_str",
                    models.CharField(
                        help_text="Config status", verbose_name="Config status"
                    ),
                ),
                (
                    "config_prefix",
                    models.CharField(
                        help_text="Config prefix", verbose_name="Config prefix"
                    ),
                ),
                (
                    "config_keys",
                    models.JSONField(
                        help_text="Config keys", verbose_name="Config keys"
                    ),
                ),
                (
                    "missing_config_keys",
                    models.JSONField(
                        help_text="Missing config keys",
                        verbose_name="Missing config keys",
                    ),
                ),
                (
                    "is_config_ready",
                    models.BooleanField(
                        help_text="Is config ready", verbose_name="Is config ready"
                    ),
                ),
                (
                    "package_status_str",
                    models.CharField(
                        help_text="Package status", verbose_name="Package status"
                    ),
                ),
                (
                    "required_packages",
                    models.JSONField(
                        help_text="Required packages", verbose_name="Required packages"
                    ),
                ),
                (
                    "missing_packages",
                    models.JSONField(
                        help_text="Missing packages", verbose_name="Missing packages"
                    ),
                ),
                (
                    "are_packages_installed",
                    models.BooleanField(
                        help_text="Are packages installed",
                        verbose_name="Are packages installed",
                    ),
                ),
                (
                    "service_status_str",
                    models.CharField(
                        help_text="Service status", verbose_name="Service status"
                    ),
                ),
                (
                    "missing_services",
                    models.JSONField(
                        help_text="Missing services", verbose_name="Missing services"
                    ),
                ),
                (
                    "services",
                    models.JSONField(help_text="Services", verbose_name="Services"),
                ),
                (
                    "are_services_implemented",
                    models.BooleanField(
                        help_text="Are services implemented",
                        verbose_name="Are services implemented",
                    ),
                ),
            ],
            options={
                "verbose_name": "CompanyAtlas Provider",
                "verbose_name_plural": "CompanyAtlas Providers",
                "ordering": ["-priority", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasVirtualCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Virtual Company",
                "verbose_name_plural": "Virtual Companies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasVirtualDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Document",
                "verbose_name_plural": "Virtual Documents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasVirtualEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Event",
                "verbose_name_plural": "Virtual Events",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Provider name (e.g., nominatim)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Provider display name",
                        max_length=255,
                        verbose_name="Display name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provider description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "required_packages",
                    models.JSONField(
                        default=list,
                        help_text="Required Python packages",
                        verbose_name="Required packages",
                    ),
                ),
                (
                    "status_url",
                    models.URLField(
                        blank=True,
                        help_text="Provider status URL",
                        verbose_name="Status URL",
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(
                        blank=True,
                        help_text="Provider documentation URL",
                        verbose_name="Documentation URL",
                    ),
                ),
                (
                    "site_url",
                    models.URLField(
                        blank=True,
                        help_text="Provider website URL",
                        verbose_name="Site URL",
                    ),
                ),
                (
                    "config_keys",
                    models.JSONField(
                        default=list,
                        help_text="Configuration keys",
                        verbose_name="Config keys",
                    ),
                ),
                (
                    "config_required",
                    models.JSONField(
                        default=list,
                        help_text="Required configuration keys",
                        verbose_name="Config required",
                    ),
                ),
                (
                    "config_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Configuration prefix",
                        max_length=255,
                        verbose_name="Config prefix",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        default=list,
                        help_text="Available services",
                        verbose_name="Services",
                    ),
                ),
                (
                    "are_packages_installed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether required packages are installed",
                        verbose_name="Packages installed",
                    ),
                ),
                (
                    "are_services_implemented",
                    models.BooleanField(
                        default=False,
                        help_text="Whether services are implemented",
                        verbose_name="Services implemented",
                    ),
                ),
                (
                    "is_config_ready",
                    models.BooleanField(
                        default=False,
                        help_text="Whether configuration is ready",
                        verbose_name="Config ready",
                    ),
                ),
                (
                    "missing_packages",
                    models.JSONField(
                        default=list,
                        help_text="Missing packages",
                        verbose_name="Missing packages",
                    ),
                ),
                (
                    "missing_config_keys",
                    models.JSONField(
                        default=list,
                        help_text="Missing config keys",
                        verbose_name="Missing config keys",
                    ),
                ),
                (
                    "missing_services",
                    models.JSONField(
                        default=list,
                        help_text="Missing services",
                        verbose_name="Missing services",
                    ),
                ),
            ],
            options={
                "verbose_name": "CompanyAtlas Provider",
                "verbose_name_plural": "CompanyAtlas Providers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="N/A",
                        help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')",
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="NA",
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company name", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Company description",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="djcompanyat_created_fb5940_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="N/A",
                        help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')",
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="NA",
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "address",
                    djgeoaddress.fields.GeoaddressField(
                        help_text="Company address", verbose_name="Address"
                    ),
                ),
                (
                    "is_headquarters",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this address is the company's headquarters",
                        verbose_name="Is headquarters",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this address belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="djcompanyatlas.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Address",
                "verbose_name_plural": "Company Addresses",
                "indexes": [
                    models.Index(
                        fields=["company", "address"],
                        name="djcompanyat_company_cfb9b3_idx",
                    ),
                    models.Index(
                        fields=["company", "is_headquarters"],
                        name="djcompanyat_company_2d2d90_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="N/A",
                        help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')",
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="NA",
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="Type of data (e.g., denomination, siren, capital, employees)",
                        max_length=100,
                        verbose_name="Data Type",
                    ),
                ),
                (
                    "value",
                    models.TextField(help_text="Data value", verbose_name="Value"),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        help_text="Type of the value (str, int, float, json)",
                        max_length=10,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this data belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="djcompanyatlas.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Data",
                "verbose_name_plural": "Company Data",
                "indexes": [
                    models.Index(
                        fields=["company", "country_code"],
                        name="djcompanyat_company_131081_idx",
                    ),
                    models.Index(
                        fields=["data_type"], name="djcompanyat_data_ty_194c44_idx"
                    ),
                ],
                "unique_together": {("company", "source", "country_code", "data_type")},
            },
        ),
        migrations.CreateModel(
            name="CompanyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="N/A",
                        help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')",
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="NA",
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Type of document (e.g., bodacc, kbis, balo)",
                        max_length=100,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Document date",
                        null=True,
                        verbose_name="Date",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL to access the document",
                        verbose_name="URL",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Document content or summary",
                        verbose_name="Content",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional document metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="djcompanyatlas.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Document",
                "verbose_name_plural": "Company Documents",
                "indexes": [
                    models.Index(
                        fields=["company", "country_code"],
                        name="djcompanyat_company_d9602d_idx",
                    ),
                    models.Index(
                        fields=["document_type"], name="djcompanyat_documen_053f89_idx"
                    ),
                    models.Index(fields=["date"], name="djcompanyat_date_d88d04_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="N/A",
                        help_text="Backend source (e.g., 'insee', 'pappers', 'infogreffe')",
                        max_length=100,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        default="NA",
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of event (e.g., status_change, modification, capital_change)",
                        max_length=100,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Event title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Event date",
                        null=True,
                        verbose_name="Date",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Event description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="djcompanyatlas.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Event",
                "verbose_name_plural": "Company Events",
                "indexes": [
                    models.Index(
                        fields=["company", "country_code"],
                        name="djcompanyat_company_7504be_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="djcompanyat_event_t_cd2898_idx"
                    ),
                    models.Index(fields=["date"], name="djcompanyat_date_16f749_idx"),
                ],
            },
        ),
    ]
