# Generated by Django 6.0.1 on 2026-01-27 16:09

import django.db.models.deletion
import djgeoaddress.fields
import namedid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyAtlasProviderModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Provider name (e.g., insee)",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Name",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Provider display name", verbose_name="Display Name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Provider description", verbose_name="Description"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Provider priority", verbose_name="Priority"
                    ),
                ),
                (
                    "config_status_str",
                    models.CharField(
                        help_text="Config status", verbose_name="Config status"
                    ),
                ),
                (
                    "config_prefix",
                    models.CharField(
                        help_text="Config prefix", verbose_name="Config prefix"
                    ),
                ),
                (
                    "config_keys",
                    models.JSONField(
                        help_text="Config keys", verbose_name="Config keys"
                    ),
                ),
                (
                    "missing_config_keys",
                    models.JSONField(
                        help_text="Missing config keys",
                        verbose_name="Missing config keys",
                    ),
                ),
                (
                    "is_config_ready",
                    models.BooleanField(
                        help_text="Is config ready", verbose_name="Is config ready"
                    ),
                ),
                (
                    "package_status_str",
                    models.CharField(
                        help_text="Package status", verbose_name="Package status"
                    ),
                ),
                (
                    "required_packages",
                    models.JSONField(
                        help_text="Required packages", verbose_name="Required packages"
                    ),
                ),
                (
                    "missing_packages",
                    models.JSONField(
                        help_text="Missing packages", verbose_name="Missing packages"
                    ),
                ),
                (
                    "are_packages_installed",
                    models.BooleanField(
                        help_text="Are packages installed",
                        verbose_name="Are packages installed",
                    ),
                ),
                (
                    "service_status_str",
                    models.CharField(
                        help_text="Service status", verbose_name="Service status"
                    ),
                ),
                (
                    "missing_services",
                    models.JSONField(
                        help_text="Missing services", verbose_name="Missing services"
                    ),
                ),
                (
                    "services",
                    models.JSONField(help_text="Services", verbose_name="Services"),
                ),
                (
                    "are_services_implemented",
                    models.BooleanField(
                        help_text="Are services implemented",
                        verbose_name="Are services implemented",
                    ),
                ),
                (
                    "geo_data",
                    models.CharField(
                        help_text="Data source", verbose_name="Data source"
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
                "ordering": ["-priority", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasVirtualCompany",
            fields=[
                (
                    "companyatlas_id",
                    models.CharField(
                        help_text="Companyatlas ID",
                        max_length=500,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Companyatlas ID",
                    ),
                ),
                (
                    "denomination",
                    models.CharField(
                        blank=True,
                        help_text="Denomination",
                        max_length=500,
                        verbose_name="Denomination",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference",
                        max_length=255,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country",
                        max_length=500,
                        verbose_name="Country",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Address",
                        max_length=500,
                        verbose_name="Address",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="Data source",
                        max_length=500,
                        verbose_name="Data source",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        blank=True,
                        help_text="Backend display name",
                        max_length=500,
                        verbose_name="Backend display name",
                    ),
                ),
                (
                    "backend_name",
                    models.CharField(
                        blank=True,
                        help_text="Simple backend name (e.g., insee)",
                        max_length=500,
                        verbose_name="Simple backend name (e.g., insee)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Company",
                "verbose_name_plural": "Virtual Companies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasVirtualDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Document",
                "verbose_name_plural": "Virtual Documents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasVirtualEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virtual Event",
                "verbose_name_plural": "Virtual Events",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')",
                        max_length=100,
                        null=True,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        null=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "denomination",
                    models.CharField(
                        help_text="Company denomination",
                        max_length=255,
                        verbose_name="Denomination",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Company code", max_length=255, verbose_name="Code"
                    ),
                ),
                (
                    "named_id",
                    namedid.fields.NamedIDField(
                        help_text="Named ID",
                        source_fields=["denomination", "code"],
                        unique=True,
                        verbose_name="Named ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="djcompanyat_created_d85b20_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')",
                        max_length=100,
                        null=True,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        null=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "address",
                    djgeoaddress.fields.GeoaddressField(
                        help_text="Company address", verbose_name="Address"
                    ),
                ),
                (
                    "is_headquarters",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this address is the company's headquarters",
                        verbose_name="Is headquarters",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this address belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="djcompanyatlas.companyatlascompany",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Address",
                "verbose_name_plural": "Company Addresses",
                "indexes": [
                    models.Index(
                        fields=["company", "address"],
                        name="djcompanyat_company_cfb9b3_idx",
                    ),
                    models.Index(
                        fields=["company", "is_headquarters"],
                        name="djcompanyat_company_2d2d90_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')",
                        max_length=100,
                        null=True,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        null=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "data_type",
                    models.CharField(
                        help_text="Type of data (e.g., denomination, siren, capital, employees)",
                        max_length=100,
                        verbose_name="Data Type",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("json", "JSON"),
                        ],
                        default="str",
                        help_text="Type of the value (str, int, float, json)",
                        max_length=10,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "value",
                    models.TextField(help_text="Data value", verbose_name="Value"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this data belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="djcompanyatlas.companyatlascompany",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Data",
                "verbose_name_plural": "Company Data",
                "indexes": [
                    models.Index(
                        fields=["company", "country_code"],
                        name="djcompanyat_company_c6bdd9_idx",
                    ),
                    models.Index(
                        fields=["data_type"], name="djcompanyat_data_ty_1fa5fd_idx"
                    ),
                ],
                "unique_together": {("company", "source", "country_code", "data_type")},
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')",
                        max_length=100,
                        null=True,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        null=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Type of document (e.g., bodacc, kbis, balo)",
                        max_length=100,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Document date",
                        null=True,
                        verbose_name="Date",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL to access the document",
                        verbose_name="URL",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Document content or summary",
                        verbose_name="Content",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="djcompanyatlas.companyatlascompany",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Document",
                "verbose_name_plural": "Company Documents",
                "indexes": [
                    models.Index(
                        fields=["company", "country_code"],
                        name="djcompanyat_company_be29cd_idx",
                    ),
                    models.Index(
                        fields=["document_type"], name="djcompanyat_documen_a7e677_idx"
                    ),
                    models.Index(fields=["date"], name="djcompanyat_date_22a122_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyAtlasEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')",
                        max_length=100,
                        null=True,
                        verbose_name="Source",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO country code (e.g., FR, US, GB)",
                        max_length=2,
                        null=True,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of event (e.g., status_change, modification, capital_change)",
                        max_length=100,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Event title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Event date",
                        null=True,
                        verbose_name="Date",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Event description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="djcompanyatlas.companyatlascompany",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Event",
                "verbose_name_plural": "Company Events",
                "indexes": [
                    models.Index(
                        fields=["company", "country_code"],
                        name="djcompanyat_company_b73b12_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="djcompanyat_event_t_3cd0e1_idx"
                    ),
                    models.Index(fields=["date"], name="djcompanyat_date_9f6f37_idx"),
                ],
            },
        ),
    ]
