# Generated by Django 6.0 on 2026-02-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcompanyatlas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyatlasdata',
            name='company',
            field=models.ForeignKey(help_text='Company this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='to_companyatlasdata', to='djcompanyatlas.companyatlascompany', verbose_name='Company'),
        ),
    ]
