# Generated by Django 6.0 on 2026-02-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcompanyatlas', '0002_alter_companyatlasdata_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyatlasaddress',
            options={'ordering': ['-is_headquarters', '-created_at'], 'verbose_name': 'Company Address', 'verbose_name_plural': 'Company Addresses'},
        ),
        migrations.AlterModelOptions(
            name='companyatlasdata',
            options={'ordering': ['data_type', '-created_at'], 'verbose_name': 'Company Data', 'verbose_name_plural': 'Company Data'},
        ),
        migrations.AlterField(
            model_name='companyatlasaddress',
            name='company',
            field=models.ForeignKey(help_text='Company this address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='to_companyatlasaddress', to='djcompanyatlas.companyatlascompany', verbose_name='Company'),
        ),
    ]
