# Generated by Django 6.0 on 2026-02-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcompanyatlas', '0003_alter_companyatlasaddress_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAtlasPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text="Backend source (e.g., 'insee', 'bodacc', 'inpi')", max_length=100, null=True, verbose_name='Source')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code (e.g., FR, US, GB)', max_length=2, null=True, verbose_name='Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('officer_or_owner', models.CharField(choices=[('officer', 'Officer'), ('owner', 'Ultimate Beneficial Owner')], help_text='Type of person (officer, owner)', max_length=100, verbose_name='Person Type')),
                ('physical_or_moral', models.CharField(choices=[('physical', 'Physical'), ('moral', 'Moral')], help_text='Physical or moral person', max_length=100, verbose_name='Physical or Moral')),
                ('is_joint_ownership', models.BooleanField(default=False, help_text='Whether the person is a joint owner (held in indivision)', verbose_name='Is joint ownership')),
                ('denomination', models.CharField(help_text='Denomination of the person', max_length=100, verbose_name='Denomination')),
                ('code', models.CharField(help_text='Code of the person', max_length=100, verbose_name='Code')),
                ('first_name', models.CharField(help_text='First name of the person', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last name of the person', max_length=100, verbose_name='Last Name')),
                ('birth_date', models.DateField(blank=True, help_text='Birth date of the person', null=True, verbose_name='Birth Date')),
                ('company', models.ForeignKey(help_text='Company this person belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='to_companyatlasperson', to='djcompanyatlas.companyatlascompany', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Person',
                'verbose_name_plural': 'Company Persons',
                'ordering': ['officer_or_owner', 'physical_or_moral', '-created_at'],
                'indexes': [models.Index(fields=['company', 'officer_or_owner', 'physical_or_moral'], name='djcompanyat_company_22fc04_idx')],
            },
        ),
    ]
